apiVersion: apps/v1
kind: Deployment
metadata:
  name: processing
spec:
  selector:
    matchLabels:
      app: processing
  template:
    metadata:
      labels:
        app: processing
    spec:
      containers:
      - name: processing
        image: processing:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
        env:
          - name: EMAIL_HOST
            value: email.default.svc.cluster.local:50051
